### PR TITLE
Pixel battery icons

### PR DESCRIPTION
**Pull request by Prospector**

### CODE REVIEW

**Comment by Prospector** [comment]
After using the icons for 12 hours I'm not sure my fast charging one is great. Maybe don't merge this yet, I might have another go at the icon tomorrow

**Comment by Prospector** [comment]
Actually, I guess it's alright to merge. not a priority though, very small change lol

**Comment by valentind44** [comment]
Thanks a lot for your contributions. I'm glad to see some new additions to LGTweaks :)

**Comment by Prospector** [comment]
Yeah, no problem. I'd say don't worry about releasing just the battery icon as an update yet. I'll get around to adding a few more things soon.

**Comment by valentind44** [comment]
Great! I'm looking forward to your next commit.

**Comment by sweatedpear** [comment]
Just wondering if there's any new news on this. Been using it for about 6 months and would love the battery icon themed but not too sure on how to do it myself.

**Pull request merged**
